name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cd website && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: cd website && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: cd website && php artisan key:generate
    - name: Directory Permissions
      run: cd website && chmod -R 777 storage bootstrap/cache
    - name: Verify MySQL connection
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.p
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        MYSQL_DATABASE: test_db
        DB_USERNAME: user
        DB_PASSWORD: secret
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: cd website && php artisan test
